spring:
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/testdata
  datasource:
    url: jdbc:h2:mem:db
    username: desenvolvimento
    password: desenvolvimento
    driver-class-name: 'org.h2.Driver'
    hikari:
      pool-name: 'crud_poc_pessoa'
      connection-timeout: 6000
      minimum-idle: 1
      connection-init-sql: SELECT 1
      auto-commit: false
      maximum-pool-size: 20
  jpa:
    database: h2
    show-sql: false
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect